# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

 flutter_application_path = '../flutter_boost_dart_demo'
 load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterBoostDemo' do
  use_frameworks!

  install_all_flutter_pods(flutter_application_path)

end